name: Build and Deploy Portfolio Website to K3s

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }} 

    - name: Build and push Docker image to GHCR
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: . 
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}:latest,ghcr.io/${{ github.repository }}:${{ github.sha }}
        
        platforms: linux/amd64,linux/arm64

    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: '3.8.1' # Specify a Helm version

    - name: Set Kubeconfig
      run: |
        mkdir -p ~/.kube
        # Decode the base64 secret and write it to the file
        echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config
        chmod 600 ~/.kube/config
        # Verify kubectl can connect
        kubectl cluster-info
        kubectl get nodes

    - name: Deploy to Kubernetes with Helm
      run: |
        # Use the portfolio-website-chart directory
        helm upgrade --install portfolio-website ./portfolio-website-chart \
          --set image.tag=${{ github.sha }} \
          --set image.repository=ghcr.io/${{ github.repository }} \
          --set service.targetPort=3000 \ # <--- Explicitly set targetPort for clarity
          --set ingress.hosts[0].host=vishvesh.me \ # <--- Set your domain
          --set ingress.tls[0].hosts[0]=vishvesh.me \ # <--- Set your domain for TLS
          --wait # Wait for the deployment to be ready
